#20250612更新
amcl:
  ros__parameters:
    use_sim_time: false
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    scan_topic: "/scan"
    update_min_d: 0.2  # 近い: scan_matching に似た
    update_min_a: 0.2
    min_particles: 200
    max_particles: 5000
    resample_interval: 1
    transform_tolerance: 0.5
    recovery_alpha_slow: 0.001
    recovery_alpha_fast: 0.1
    laser_max_range: 40.0  # ← slam_toolbox設定より流用
    laser_min_range: 0.1   # ← slam_toolbox設定より流用
    tf_broadcast: true
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2

# --- ★重要：map_serverからyaml_filenameを削除 ---
# yaml_filenameはローンチファイルから渡されるため、ここで指定すると競合やエラーの原因になります。
map_server:
  ros__parameters:
    use_sim_time: False

bt_navigator:
  ros__parameters:
    use_sim_time: false

controller_server:
  ros__parameters:
    use_sim_time: false

planner_server:
  ros__parameters:
    use_sim_time: false

behavior_server:
  ros__parameters:
    use_sim_time: false

local_costmap:
  ros__parameters:
    use_sim_time: false
    robot_base_frame: "base_footprint"
    footprint: "[[0.3, 0.3], [0.3, -0.3], [-0.3, -0.3], [-0.3, 0.3]]"
    resolution: 0.05
    width: 3
    height: 3
    plugins: ["obstacle_layer", "inflation_layer"]

global_costmap:
  ros__parameters:
    use_sim_time: false
    robot_base_frame: "base_footprint"
    footprint: "[[0.3, 0.3], [0.3, -0.3], [-0.3, -0.3], [-0.3, 0.3]]"
    resolution: 0.05
    width: 10
    height: 10
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"

controller_server:
  ros__parameters:
    controller_frequency: 10.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
