amcl:
  ros__parameters:
    use_sim_time: false
    min_particles: 100
    max_particles: 500
    transform_tolerance: 0.2
    update_min_d: 0.1
    update_min_a: 0.05
    laser_max_range: 8.0
map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: /home/user/maps/static_map.yaml
    threshold: 0.4
