version: '3.8'

services:
  # この環境のサービス名
  nav2_demo:
    image: nav2-practice
    build:
      context: ../3_dockerfiles_robot
      dockerfile: dockerfile.nav2
    container_name: nav2_demo

    # --- ここが最重要：デバッグモードへの切り替え ---
    # コンテナのメインの仕事を「無限に待機する」ことに上書きする
    # これにより、ローンチファイルのエラーでコンテナが落ちなくなる
    command: ["sleep", "infinity"]

    volumes:
      # bind "host folder":"docker folder"
      - ${HOME}/.ssh:/root/.ssh
      - ./common:/common # common scripts
      - $ACSL_WORK_DIR/1_launcher:/common/ros_launcher
      - /dev:/dev # GPIO and USB devices
      - vscode-server:/root/.vscode-server # VScode setting (preserve VScode extension)
      - $ACSL_WORK_DIR/2_ros_packages:/root/ros2_ws/src/ros_packages
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      # WSL
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
    tty: true
    # ROS 2の通信を簡単にするため、ホストPCのネットワークをそのまま使います
    network_mode: host
    # (オプション) RVizなどGUIアプリを使いたい場合、以下のコメントを解除します
    # environment:
    #   - DISPLAY=${DISPLAY}
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPABILITIES=all
    # volumes:
    #   - /tmp/.X11-unix:/tmp/.X11-unix